backend:
  name: git-gateway
  branch: main # Make sure this matches your GitHub branch (sometimes it's 'master')

media_folder: "Website/images/uploads" # Where your drag-and-drop images will be saved
public_folder: "/images/uploads" # How the website will find those images

collections:
  - name: "blog"
    label: "Travel Blog"
    folder: "Website/blog-posts" # The CMS will automatically create this folder to save your articles
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Blog Content", name: "body", widget: "markdown"}
